### ISSUE TITLE
Handle the OpenAI API key properly.

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_publications_importer#4]
Currently it's just in the code. It's set to the empty string in the committed version.

We should handle this API key properly, either using key module to do it ourselves, or maybe the ai module to provide the client that we use to talk to OpenAI?

**Comment by rbg-lslater** [comment]
Decided to start looking into implementing the AI module for this, work so far on feature/4-properly-handle-api-key

I *think* it's in a working state, but need to figure out a way to test locally to confirm, ideally without charge. The lmstudio ai provider seems ideal, but I'm having some trouble setting it up on my local env.

**Comment by rupertj** [comment]
Thanks - this looks good to me. I'll make an MR for it so the tests run.

**Comment by rupertj** [comment]
I had to add ai_provider_openai as a dependency of the module so everything installed properly, but apart from that, I've tested this and it works nicely. Thanks!
